db_file: "bot.db"

bot_url: "https://t.me/my_new_bot_pocket_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начал тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизирован. Присылай ссылку,  а я ее сохраню."
    saved_successfully: "Это ссылка успешно сохранена"
    unhnown_command: "Я не знаю такую команду :("
  errors:
    default: "Произошла неизвестная ошибка"
    invalid_url: "Это невалидная ссылка"
    unauthorized: "Ты не авторизирован! используй команду /start"
    unable_to_save: "Увы, не удалось сохранить вашу ссылку. Попробуй ещё раз позже"

